### ISSUE TITLE
Tasks for initial release

### ISSUE THREAD

**Issue by marciot** [marciot/drunken-octopus-marlin#1]
Things to be done for initial release:

- [x] Make first successful build of Marlin on home PC (Windows 10) using WSL
- [x] Make *Drunken Octopus* logo for B&W LCD
- [ ] Wire up color LCD so I can test Color Touch Screen changes (unless someone wants to buy me a TAZ Pro :smile:).
- [x] Make *Drunken Octopus* logo for Color Touch Screen
- [x] Make *Marlin* logo for Color Touch Screen
- [x] Copy over tools from LulzBot repo, with necessary modifications
- [x] Remove LulzBot logos from repo and replace them with Marlin or *Drunken Octopus* logos
- [x] Copy over ArduinoAddons from LulzBot repos with necessary updates
- [x] Merge over LulzBot specific changes to *Drunken Octopus*
- [x] Add toolhead information to Info Menu
- [x] Simplify firmware names
- [ ] Clean up unused parameter warnings
- [ ] Create pull requests for changes which should be incorporated upstream

Tasks which I could delegate (i.e. which would not take longer to explain than to accomplish):

- [ ] Fix Makefile so it can work under WSL when username contains spaces
- [x] Remove Marlin upstream releases and tags from releases page so we can start fresh.
- [x] Write Wiki pages on building *Drunken Octopus* under WSL and Arduino IDE

**Comment by crpalmer** [comment]
I assume that you are not planning on porting any of the command line tools that Lulzbot uses for building?

**Comment by marciot** [comment]
@crpalmer: Actually, I do plan on bringing them over. I would like to run them under Windows Subsystem for Linux on my Windows 10 PC.

**Comment by crpalmer** [comment]
Oh, that's great.  I really like being able to build the firmware from my linux server via ssh.

**Comment by marciot** [comment]
@crpalmer: I am compiling using the build tools right now. So far so good. If you want to start messing around with the code, feel free. The build stuff has been pushed as of a few minutes ago.

**Comment by marciot** [comment]
Closing this issue since the first release will be made shortly.
