### ISSUE TITLE
April Release - Taz6 v3 BLTouch - Fails to upload(?) - Patreon Edition

### ISSUE THREAD

**Issue by keawepoo** [marciot/drunken-octopus-marlin#13]
### Steps to Reproduce
1. Start Cura
2. Update firmware

**Expected behavior:** 
To update the firmware...

**Actual behavior:** 
It just sits at "updating firmware"... For at least 5mins. After that I canceled the update.

#### Additional Information
https://imgur.com/a/xvHd3RX

**Comment by marciot** [comment]
The recommended flashing program for the Archim is BOSSA (https://www.shumatech.com/web/products/bossa).

With it, follow this procedure for flashing:

- Open up the Windows device manager and open "Port (COM & LPT)".
- Press and hold the "Erase" button while you tap the "Reset" button. The Device Manager should refresh show a "Bossa Program Port".
- Upload FW to that port using BOSSA with "Erase all" and "Boot to flash" checked.
- Tap the Reset button after the flash completes.
- The Device Manager should refresh again and it will show "Serial GCode 3D Printer" on a different port.

If you cannot connect to the serial port after this process, try the following:

- Try manually connecting to that port at 250000 baud using PuTTY for Windows.
- Uninstalled and deleted the drivers that windows allocates to the serial port.
- Repeat steps above.

**Comment by keawepoo** [comment]
Im sorry, I thought I had listed it as the stock board. Will this still work?

**Comment by marciot** [comment]
Oh, I'm sorry. No, those procedures are for the Archim board. For a stock (Rambo) board, you could try either one of these tools:

- https://www.hobbytronics.co.uk/arduino-xloader
- https://blog.zakkemble.net/avrdudess-a-gui-for-avrdude/

I've used the first tool, but not the second. Anyhow, the fact Cura isn't able to load the FW isn't really anything to do with Drunken Octopus. Have you tried asking for help in the Cura forums?

**Comment by keawepoo** [comment]
Its all good, It was my own oversight. What board is it listed as? Mega or Uno? Im using the xloader.
Well I also tryed lulzbot one too and it failed. That being somewhat old I dont know if it would still be a Cura issue.

**Comment by marciot** [comment]
Mega.

**Comment by keawepoo** [comment]
Baub rate 57600 or 250000??

**Comment by marciot** [comment]
I think either will work, but 250000 preferred.

**Comment by keawepoo** [comment]
at 250000, it says that upload has failed... at 57600 it just stays at "uploading..."

**Comment by marciot** [comment]
Does the printer otherwise turn on? You may have blown fuses on the board or something. Make sure the BLTouch didn't short something out. I recommend disconnecting it, as well as anything else you might have connected to the board.

**Comment by marciot** [comment]
You could also reach out to Ultimachine for ideas. At this point, it doesn't seem like it's a firmware issue, but a hardware issue of some sort.

**Comment by keawepoo** [comment]
BLTouch isnt even connected yet... Ive tried to print via octoprint and it works. but ya will do. 
Thank you.

**Comment by marciot** [comment]
That's weird. Usually flashing is a fairly straightforward process, easier on the Rambo than the Archim. Not sure why your board is being problematic.

**Comment by keawepoo** [comment]
Well I do know that theres a EPROM issue... where it doesnt save anything. I think I posted awile back about it.

**Comment by keawepoo** [comment]
> That's weird. Usually flashing is a fairly straightforward process, easier on the Rambo than the Archim. Not sure why your board is being problematic.

So I just flashed lulzbot firmware on and it worked... So that might be a issue with DO?

**Comment by marciot** [comment]
Weird. Can you try the regular TAZ 6 build from DO? 

- Marcio

**Comment by keawepoo** [comment]
I just did. I tryed the R10 standard Tilapia_SingleExtruder, That one failed. Then I tryed R9 standard Tilapia_SingleExtruder and it worked...

So it really looks like theres a issue over all in R10.

**Comment by marciot** [comment]
Interesting. I’ll see if I can look into it this weekend. Thanks.

**Comment by keawepoo** [comment]
Fixed with R11.
